# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('return', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['bio']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
